/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triphop.view;


import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import triphop.control.*;
import triphop.model.*;

/**
 *
 * @author Freyja Sigurgísladóttir, frs24@hi.is
 * @author Henrietta Þóra Magnúsdóttir, hthm6@hi.is
 */
public class MainFrame extends javax.swing.JFrame {
    private Boolean flagLang = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        String lang = Locale.getDefault().toString();
        String en = new Locale("en_GB").toString();
        if(lang.equals(en)) {
            jLanguage.setSelectedIndex(1);
        }
        JTable jResultTable = new JTable();
        flagLang = true;
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        
        StretchIcon backImg = createImg("img/back3.png");
        jBackButton.setIcon(backImg);
        StretchIcon sunImg = createImg("img/sun.png");
        jButton2.setIcon(sunImg);
        StretchIcon skiImg = createImg("img/ski.png");
        jButton3.setIcon(skiImg);
        StretchIcon golfImg = createImg("img/golf.png");
        jButton4.setIcon(golfImg);
        StretchIcon cityImg = createImg("img/city.png");
        jButton9.setIcon(cityImg);
        StretchIcon crowdImg = createImg("img/crowd.png");
        jButton10.setIcon(crowdImg);
        StretchIcon hikeImg = createImg("img/hike.png");
        jButton11.setIcon(hikeImg);
        StretchIcon familyImg = createImg("img/family.png");
        jButton12.setIcon(familyImg);
    }
    
        /**
     * Aðferð sem sækir mynd og býr hana til með StretchIcon
     * @param path
     * @return 
     */
    private static StretchIcon createImg(String path) {
        java.net.URL imgURL = MainFrame.class.getResource(path);
        if (imgURL != null) {
            return new StretchIcon(imgURL);
        } else {
            System.err.println("Fann ekki skrána " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jMainPanel = new javax.swing.JPanel();
        jBottom = new javax.swing.JPanel();
        jFrontPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFrom = new javax.swing.JTextField();
        jTo = new javax.swing.JTextField();
        departureDate = new com.github.lgooddatepicker.components.DatePicker();
        arrivalDate = new com.github.lgooddatepicker.components.DatePicker();
        jPassengers = new javax.swing.JComboBox<>();
        jSearch = new javax.swing.JButton();
        jRegistrationPanel = new javax.swing.JPanel();
        JLabel7 = new javax.swing.JLabel();
        jFirstName = new javax.swing.JTextField();
        jLastName = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jCity = new javax.swing.JTextField();
        JLabel1 = new javax.swing.JLabel();
        jZip = new javax.swing.JTextField();
        JLabel2 = new javax.swing.JLabel();
        jCountry = new javax.swing.JTextField();
        JLabel3 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        JLabel4 = new javax.swing.JLabel();
        jReset = new javax.swing.JButton();
        JLabel5 = new javax.swing.JLabel();
        jOk = new javax.swing.JButton();
        JLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jResultPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jResultTable = new javax.swing.JTable();
        jTop = new javax.swing.JPanel();
        jName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLanguage = new javax.swing.JComboBox<>();
        jBackButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 225, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBackground(new java.awt.Color(255, 225, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1450, 1000));

        jMainPanel.setBackground(new java.awt.Color(255, 225, 255));
        jMainPanel.setPreferredSize(new java.awt.Dimension(1450, 1000));

        jBottom.setBackground(new java.awt.Color(255, 225, 255));
        jBottom.setLayout(new java.awt.CardLayout());

        jFrontPanel.setBackground(new java.awt.Color(255, 225, 255));

        jPanel1.setBackground(new java.awt.Color(255, 225, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 16, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Rosewood Std", 0, 48)); // NOI18N
        jButton1.setText("TILBOÐ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1);

        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton2);

        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3);

        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton4);

        jPanel2.setBackground(new java.awt.Color(255, 225, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 16, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("triphop/view/resources/lang"); // NOI18N
        jButton5.setText(bundle.getString("Tilboð")); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton5);

        jButton6.setText(bundle.getString("Sól")); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton6);

        jButton7.setText(bundle.getString("Skíði")); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton7);

        jButton8.setText(bundle.getString("Golf")); // NOI18N
        jButton8.setToolTipText("");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton8);

        jPanel3.setBackground(new java.awt.Color(255, 225, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 16, 0));

        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton9);

        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton10);

        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton11);

        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton12);

        jPanel4.setBackground(new java.awt.Color(255, 225, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4, 16, 0));

        jButton13.setText(bundle.getString("Borg")); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton13);

        jButton14.setText(bundle.getString("Viðburðir")); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton14);

        jButton15.setText(bundle.getString("Útivist")); // NOI18N
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton15);

        jButton16.setText(bundle.getString("Fjölskylda")); // NOI18N
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton16);

        jPanel6.setBackground(new java.awt.Color(255, 225, 255));
        jPanel6.setLayout(new java.awt.GridLayout(2, 5));

        jLabel2.setText(bundle.getString("Brottfararstaður")); // NOI18N
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jPanel6.add(jLabel2);

        jLabel3.setText(bundle.getString("Áfangastaður")); // NOI18N
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jPanel6.add(jLabel3);

        jLabel4.setText(bundle.getString("Brottfarardagur")); // NOI18N
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jPanel6.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText(bundle.getString("Heimkomudagur")); // NOI18N
        jPanel6.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText(bundle.getString("Farþegar")); // NOI18N
        jPanel6.add(jLabel6);

        jFrom.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFrom.setText(bundle.getString("Reykjavík")); // NOI18N
        jPanel6.add(jFrom);

        jTo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTo.setText(bundle.getString("Allir áfangastaðir")); // NOI18N
        jTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToActionPerformed(evt);
            }
        });
        jPanel6.add(jTo);

        departureDate.setBackground(new java.awt.Color(255, 225, 255));
        departureDate.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel6.add(departureDate);

        arrivalDate.setBackground(new java.awt.Color(255, 225, 255));
        jPanel6.add(arrivalDate);

        jPassengers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jPanel6.add(jPassengers);

        jSearch.setText(bundle.getString("Leita")); // NOI18N
        jSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrontPanelLayout = new javax.swing.GroupLayout(jFrontPanel);
        jFrontPanel.setLayout(jFrontPanelLayout);
        jFrontPanelLayout.setHorizontalGroup(
            jFrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrontPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jFrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrontPanelLayout.createSequentialGroup()
                        .addGap(850, 850, 850)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrontPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrontPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrontPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrontPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrontPanelLayout.setVerticalGroup(
            jFrontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrontPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jBottom.add(jFrontPanel, "card2");

        jRegistrationPanel.setBackground(new java.awt.Color(255, 225, 255));

        JLabel7.setText("Símanúmer: ");

        jFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNameActionPerformed(evt);
            }
        });

        JLabel1.setText("Fornafn:");

        JLabel2.setText("Eftirnafn:");

        JLabel3.setText("Heimilisfang:");

        JLabel4.setText("Borg:");

        jReset.setText("Hreinsa");

        JLabel5.setText("Póstnúmer:");

        jOk.setText("Staðfesta");
        jOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkActionPerformed(evt);
            }
        });

        JLabel6.setText("Land: ");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Skráningarform");
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        javax.swing.GroupLayout jRegistrationPanelLayout = new javax.swing.GroupLayout(jRegistrationPanel);
        jRegistrationPanel.setLayout(jRegistrationPanelLayout);
        jRegistrationPanelLayout.setHorizontalGroup(
            jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationPanelLayout.createSequentialGroup()
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationPanelLayout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOk, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jRegistrationPanelLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jRegistrationPanelLayout.createSequentialGroup()
                                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(JLabel1))
                                    .addComponent(JLabel3)
                                    .addComponent(JLabel4)
                                    .addComponent(JLabel5)
                                    .addComponent(JLabel6)
                                    .addComponent(JLabel7))
                                .addGap(47, 47, 47)
                                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFirstName)
                                    .addComponent(jLastName)
                                    .addComponent(jAddress)
                                    .addComponent(jCity)
                                    .addComponent(jZip)
                                    .addComponent(jCountry)
                                    .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jRegistrationPanelLayout.setVerticalGroup(
            jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel3)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel4))
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel5)
                    .addComponent(jZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel6)
                    .addComponent(jCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel7)
                    .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReset)
                    .addComponent(jOk))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jBottom.add(jRegistrationPanel, "card3");

        jResultPanel.setBackground(new java.awt.Color(255, 225, 255));

        jResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jResultTable);

        javax.swing.GroupLayout jResultPanelLayout = new javax.swing.GroupLayout(jResultPanel);
        jResultPanel.setLayout(jResultPanelLayout);
        jResultPanelLayout.setHorizontalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jResultPanelLayout.setVerticalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );

        jBottom.add(jResultPanel, "card4");

        jTop.setBackground(new java.awt.Color(255, 225, 255));
        jTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jName.setText("T R I P H O P");
        jName.setFont(new java.awt.Font("Rosewood Std", 1, 58)); // NOI18N
        jTop.add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 335, 74));

        jLabel1.setText(bundle.getString("F i n n d u   p a k k a   f y r i r   þ i g")); // NOI18N
        jLabel1.setFont(new java.awt.Font("SignPainter", 1, 34)); // NOI18N
        jTop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 44));

        jLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Íslenska", "English" }));
        jLanguage.setBackground(new java.awt.Color(255, 225, 255));
        jLanguage.setToolTipText("");
        jLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLanguageActionPerformed(evt);
            }
        });
        jTop.add(jLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 128, 43));

        jBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackButtonMouseClicked(evt);
            }
        });
        jTop.add(jBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 40, 40));

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jTop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jMainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        String from = jFrom.getText();
        String to = jTo.getText();
        
        LocalDate d1 = departureDate.getDate();
        Date date1  = Date.from(d1.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        String strDepDate = DateFormat.getDateInstance().format(date1);
        
        LocalDate d2 = arrivalDate.getDate();
        Date date2  = Date.from(d2.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        String strArrDate = DateFormat.getDateInstance().format(date2);
        
        int passCount = jPassengers.getSelectedIndex();
        
        System.out.println("Heimaland: "+ from);
        System.out.println("Komuland: "+ to);
        System.out.println("Brottför-dagsetning: " +strDepDate);
        System.out.println("Koma-dagsetning: " + strArrDate);
        System.out.println("Fjöldi farþega: " + passCount);
        
        //Customer customer = new Customer(date1,date2,from,to,passCount,2,"Ski");
        //FlightSearcher flights = new FlightSearcher(from,to,date1,date2,passCount);
        //DayTourSearcher dayTours = new DayTourSearcher(to,date1);
        //HotelSearcher hotels = new HotelSearcher(to,date1,date2);
        //PackageManager pMan = new PackageManager(customer,flights,hotels,dayTours);
         

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Origin");
        model.addColumn("Destination");
        model.addColumn("Departure date");
        model.addColumn("Return date");
        model.addColumn("Number of passengers");
        
        model.addRow(new Object[]{from,to,strDepDate,strArrDate,passCount});
        jResultTable.setModel(model);
        
        jFrontPanel.setVisible(false); 
        jResultPanel.setVisible(true);
    }//GEN-LAST:event_jSearchActionPerformed

    private void jToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToActionPerformed

    private void jLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLanguageActionPerformed
        if(flagLang) {    
            JComboBox cb = (JComboBox)evt.getSource();
            String lang = (String)cb.getSelectedItem();

            if("English".equals(lang)) {
                dispose();
                Locale l = new Locale("en_GB");
                Locale.setDefault(l); 
                MainFrame h;
                h = new MainFrame();
                h.setVisible(true);
            }
            else {
                dispose();
                Locale l = new Locale("is_IS");
                Locale.setDefault(l);
                MainFrame h;
                h = new MainFrame();
                h.setVisible(true);
            }
        }
    }//GEN-LAST:event_jLanguageActionPerformed

    private void jFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNameActionPerformed

    private void jOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOkActionPerformed

    private void jBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackButtonMouseClicked
       
        if(jResultPanel.isVisible()==true) {
            jResultPanel.setVisible(false);
            jFrontPanel.setVisible(true);
        }
        if(jRegistrationPanel.isVisible()==true) {
            jRegistrationPanel.setVisible(false);
            jFrontPanel.setVisible(true);
        }
        
    }//GEN-LAST:event_jBackButtonMouseClicked

    public void showPackage(ArrayList<String[]> packages) {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JLabel JLabel4;
    private javax.swing.JLabel JLabel5;
    private javax.swing.JLabel JLabel6;
    private javax.swing.JLabel JLabel7;
    private com.github.lgooddatepicker.components.DatePicker arrivalDate;
    private com.github.lgooddatepicker.components.DatePicker departureDate;
    private javax.swing.JTextField jAddress;
    private javax.swing.JLabel jBackButton;
    private javax.swing.JPanel jBottom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jCity;
    private javax.swing.JTextField jCountry;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JTextField jFrom;
    private javax.swing.JPanel jFrontPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jLanguage;
    private javax.swing.JTextField jLastName;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JLabel jName;
    private javax.swing.JButton jOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox<String> jPassengers;
    private javax.swing.JTextField jPhone;
    private javax.swing.JPanel jRegistrationPanel;
    private javax.swing.JButton jReset;
    private javax.swing.JPanel jResultPanel;
    private javax.swing.JTable jResultTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearch;
    private javax.swing.JTextField jTo;
    private javax.swing.JPanel jTop;
    private javax.swing.JTextField jZip;
    // End of variables declaration//GEN-END:variables
}
