/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triphop.ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author henny
 */
public class RegistrationPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPanel
     */
    public RegistrationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlfornafn = new javax.swing.JLabel();
        jleftirnafn = new javax.swing.JLabel();
        jlheimilisfang = new javax.swing.JLabel();
        jlborg = new javax.swing.JLabel();
        jlpostnumer = new javax.swing.JLabel();
        jlland = new javax.swing.JLabel();
        jlsimanumer = new javax.swing.JLabel();
        tffornafn = new javax.swing.JTextField();
        tfeftirnafn = new javax.swing.JTextField();
        tfheimilisfang = new javax.swing.JTextField();
        tfborg = new javax.swing.JTextField();
        tfpostnumer = new javax.swing.JTextField();
        tfland = new javax.swing.JTextField();
        tfsimanumer = new javax.swing.JTextField();
        jbhreinsa = new javax.swing.JButton();
        jbstadfesta = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(954, 797));

        jlfornafn.setText("Fornafn:");

        jleftirnafn.setText("Eftirnafn:");

        jlheimilisfang.setText("Heimilisfang:");

        jlborg.setText("Borg:");

        jlpostnumer.setText("Póstnúmer:");

        jlland.setText("Land: ");

        jlsimanumer.setText("Símanúmer: ");

        jbhreinsa.setText("Hreinsa");

        jbstadfesta.setText("Staðfesta");
        jbstadfesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbstadfestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(289, Short.MAX_VALUE)
                        .addComponent(jbhreinsa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbstadfesta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jleftirnafn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addComponent(jlfornafn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jlheimilisfang)
                            .addComponent(jlborg)
                            .addComponent(jlpostnumer)
                            .addComponent(jlland)
                            .addComponent(jlsimanumer))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tffornafn)
                            .addComponent(tfeftirnafn)
                            .addComponent(tfheimilisfang)
                            .addComponent(tfborg)
                            .addComponent(tfpostnumer)
                            .addComponent(tfland)
                            .addComponent(tfsimanumer, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfornafn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffornafn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jleftirnafn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfeftirnafn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlheimilisfang)
                    .addComponent(tfheimilisfang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfborg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlborg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlpostnumer)
                    .addComponent(tfpostnumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlland)
                    .addComponent(tfland, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlsimanumer)
                    .addComponent(tfsimanumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbhreinsa)
                    .addComponent(jbstadfesta))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbstadfestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbstadfestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbstadfestaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbhreinsa;
    private javax.swing.JButton jbstadfesta;
    private javax.swing.JLabel jlborg;
    private javax.swing.JLabel jleftirnafn;
    private javax.swing.JLabel jlfornafn;
    private javax.swing.JLabel jlheimilisfang;
    private javax.swing.JLabel jlland;
    private javax.swing.JLabel jlpostnumer;
    private javax.swing.JLabel jlsimanumer;
    private javax.swing.JTextField tfborg;
    private javax.swing.JTextField tfeftirnafn;
    private javax.swing.JTextField tffornafn;
    private javax.swing.JTextField tfheimilisfang;
    private javax.swing.JTextField tfland;
    private javax.swing.JTextField tfpostnumer;
    private javax.swing.JTextField tfsimanumer;
    // End of variables declaration//GEN-END:variables
}
